// redux/components/Todos.tsx
import React, { useEffect, useState } from 'react';
import { useAppDispatch, useAppSelector } from '../store/hooks';
import { fetchTodos, addTodo, toggleTodo, clear } from '../features/todosSlice';

const Todos = () => {
  const { items, status } = useAppSelector(state => state.todos);
  const dispatch = useAppDispatch();
  const [text, setText] = useState('');

  useEffect(() => {
    if (items.length === 0) dispatch(fetchTodos());
  }, []);

  return (
    <section style={{ marginTop: '1rem', padding: '1rem', border: '1px solid #eee' }}>
      <h2>Todos</h2>
      <div>
        <input value={text} onChange={e => setText(e.target.value)} placeholder="New todo..." />
        <button onClick={() => { if (text.trim()) { dispatch(addTodo(text)); setText(''); }}}>Add</button>
        <button onClick={() => dispatch(clear())} style={{ marginLeft: '0.5rem' }}>Clear</button>
      </div>
      <div style={{ marginTop: '0.5rem' }}>
        {status === 'loading' ? <div>Loading...</div> : items.map(t => (
          <div key={t.id}>
            <input type="checkbox" checked={t.completed} onChange={() => dispatch(toggleTodo(t.id))} />
            <span style={{ marginLeft: '0.5rem', textDecoration: t.completed ? 'line-through' : 'none' }}>{t.title}</span>
          </div>
        ))}
      </div>
      <div style={{ marginTop: '0.5rem' }}>
        <strong>Completed:</strong> {items.filter(t => t.completed).length} / {items.length}
      </div>
    </section>
  );
};

export default Todos;

// pinia/components/Todos.vue
<template>
  <div class="card">
    <h3>Todos</h3>

    <div style="display:flex;gap:8px;margin-bottom:8px">
      <input v-model="text" placeholder="New todo" />
      <button @click="addTodo">Add</button>
      <button @click="fetchSample">Fetch sample</button>
    </div>

    <ul>
      <li v-for="t in todos" :key="t.id" style="display:flex;gap:8px;align-items:center">
        <input type="checkbox" :checked="t.done" @change="toggle(t.id)" />
        <span :style="{ textDecoration: t.done ? 'line-through' : 'none' }">{{ t.text }}</span>
        <button style="margin-left:auto" @click="remove(t.id)">Remove</button>
      </li>
    </ul>

    <small>Unfinished: {{ unfinishedCount }}</small>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useTodoStore } from '~/stores/todo'
const store = useTodoStore()
const text = ref('')

const { todos, unfinishedCount, loading } = storeToRefs(store)
const { add, toggle, remove, fetchSample } = store

function addTodo() {
  if (!text.value.trim()) return
  add(text.value.trim())
  text.value = ''
}
</script>
